name: 'Lokalise trigger PR  '
description: 'Triggers build on Lokalise that creates a PR '
inputs:
  LOKALISE_API_KEY:  # Lokalise API key
    description: 'API KEY'
    required: true
  LOKALISE_PROJECT_KEY: #Lokalise Projekt key 
    description: "Project key"
    required: true
outputs:
  result: # id of output
    description: 'display wether it when good or not'
runs:
  using: 'node20'
  main: 'dist/index.js'
